# Generated by Django 5.2.8 on 2026-01-16 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="训练日期"
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("drill", "基礎"),
                            ("match", "試合"),
                            ("footwork", "步伐特训"),
                            ("gym", "力量体能"),
                        ],
                        max_length=20,
                        verbose_name="训练项目",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(help_text="分钟", verbose_name="时长(分钟)"),
                ),
                (
                    "feeling",
                    models.CharField(
                        choices=[
                            ("great", "状态爆表"),
                            ("good", "感觉不错"),
                            ("tired", "累瘫了"),
                            ("pain", "带伤坚持"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="训练心得/备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
