# Generated by Django 5.2.8 on 2026-01-17 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrecord",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="練習日"
            ),
        ),
        migrations.AlterField(
            model_name="trainingrecord",
            name="duration",
            field=models.IntegerField(help_text="分", verbose_name="練習時間(分)"),
        ),
        migrations.AlterField(
            model_name="trainingrecord",
            name="feeling",
            field=models.CharField(
                choices=[
                    ("great", "好調"),
                    ("good", "普通"),
                    ("tired", "疲れた"),
                    ("pain", "痛みあり"),
                ],
                default="good",
                max_length=20,
                verbose_name="コンディション",
            ),
        ),
        migrations.AlterField(
            model_name="trainingrecord",
            name="memo",
            field=models.TextField(blank=True, verbose_name="練習メモ/反省点"),
        ),
        migrations.AlterField(
            model_name="trainingrecord",
            name="training_type",
            field=models.CharField(
                choices=[
                    ("drill", "基礎"),
                    ("match", "試合"),
                    ("footwork", "フットワーク"),
                    ("gym", "筋トレ"),
                ],
                max_length=20,
                verbose_name="メニュー",
            ),
        ),
    ]
